export * from './files.interface'
export * from './menu.interface'
export * from './plato.interface'
export * from './registrar-cliente.interface'
export * from './registrar-usuario.interface'
export * from './restaurante.interface'
export * from './resultadoPaginado.interface'
export * from './usuarioToken.interface'
