export enum TypePlantillaEmail {
  CONFIRMAR_RESERVA_CLIENTE = 'CONFIRMAR_RESERVA_CLIENTE',
  CANCELADA_RESERVA_CLIENTE = 'CANCELADA_RESERVA_CLIENTE',
  RESERVA_RECHAZADA_CLIENTE = 'RESERVA_RECHAZADA_CLIENTE',
  RESERVA_PENDIENTE_RESTAURANTE = 'RESERVA_PENDIENTE_RESTAURANTE',
  RESERVA_PENDIENTE_CLIENTE = 'RESERVA_PENDIENTE_CLIENTE'
}

export enum AsuntoEmailReservas {
  'ACEPTADA' = 'Reserva aceptada',
  'RECHAZADA' = 'Reserva rechaazada',
  'PEDIENTE' = 'Reserva pendiente',
  'CANCELADA' = 'Reserva cancelada'
}
